name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: deploy-production
  cancel-in-progress: true

jobs:
  deploy:
    name: Build and deploy to Vercel
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Pull Vercel environment information
        run: npx vercel pull --yes --environment=production --token ${{ secrets.VERCEL_TOKEN }}

      - name: Create production build
        run: npx vercel build --prod --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to production
        run: npx vercel deploy --prebuilt --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
